# Address that your LiteLLM server is listening on.
backend_url: http://127.0.0.1:8082

# Address that litellm-queue listens on
listen_address: 127.0.0.1:8080

models:
  - name: gpt-4.1 # The name of the model that your clients call.
    size: 10 # Amount of concurrent requests for this model.
  - name: Beepo-22B
    size: 1